baseurl = "http://anderspitman.com/"
languageCode = "en-us"
title = "Anders Pitman's blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
#disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = "UA-89445274-1"
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
#themesDir = "../.."

[params]
    site_author = "Anders Pitman"
    site_description = "Personal Blog"
    location = "USA, Arizona, Tempe"
    # Link custom assets relative to /static
    avatar = "img/portrait.jpg"
    header_background = "img/colorado.jpg"
    header_title = ""
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-89445274-1"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "anderspitman"
    facebook  = ""
    linkedin  = "anderspitman"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "anderspitman"
    gplus     = ""
